#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST
